version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_NAME
    ports:
      - $POSTGRESDB_LOCAL_PORT:$POSTGRESDB_DOCKER_PORT
    volumes:
      - db:/var/lib/postgres

  app:
    depends_on:
      - postgresdb
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=postgresdb
      - DB_USER=$POSTGRESDB_USER
      - DB_PASSWORD=$POSTGRESDB_PASSWORD
      - DB_NAME=$POSTGRESDB_NAME
      - DB_PORT=$POSTGRESDB_DOCKER_PORT
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes:
      - ./backend/:/backend
      - /backend/node_modules
    stdin_open: true
    tty: true

  client:
    depends_on:
      - app
    build: ./web-client
    restart: unless-stopped
    env_file: ./.env
    environment:
      - BACKEND_URL=$CLIENT_BROWSER_URL
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    volumes:
      - ./web-client:/web-client
      - /web-client/node_modules
    tty: true
volumes: 
  db: